services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis
# puedes crear desde el dockerfile con build o 
# puedes usar directo la imagen de redis como lo dejo en los comentarios:
  redis-app:  # redis
    build: ./redis # image: "redis:6.2.5"
    ports:
      - "6379:6379"